### ISSUE TITLE
Support for nodes management interfaces (oobm network with participating host)

### ISSUE THREAD

**Issue by saenzpa** [HPENetworking/topology_docker#9]
This was reported by Wassermann, Gary <gary.wassermann@hpe.com>

> I’m trying to do some interactive testing with docker switch images.  To do that, I used test_ping.py to create a topology with two switches and two workstations.  I used the debugger to pause the test and manually interact with the switches.  What I would like to do now is use the management interface to copy files from my VM to the running switches, but I can’t find the management interface.  On docker switch instances that I create through my normal manual process, the management (oobm) interface is eth0.  From the bash shell, if I run “ifconfig –a”, I only see lo.  If I run “ip netns exec swns ifconfig –a”, I see many interfaces including ovs-netdev and bridge_normal, but I don’t think those are what I’m looking for.  I ran “dmesg | grep eth0” and the output looked essentially the same as on my docker switch instance that does have eth0.

**Comment by garymw** [comment]
Carlos,

Thanks for the tips, especially on the mounted /tmp/... directory.  That will really help.

Your comment about the reason for not having a management port is a little concerning though.  The whole point of an OOBM port is that it is not in the data plane and switches will not attempt to send packets from it (except for to a management connection).  I don't have the background in OpenSwitch yet to comment on how things are implemented here, but if what you're saying is correct, then the implementation of OOBM support needs to be re-examined!

--Gary

**Comment by garymw** [comment]
Thanks, Carlos.  I'll look forward to seeing how this develops.

I appreciate the background info.  I would have thought that from the perspective of the image, whether it is running in docker or on actual hardware would not have mattered for how packets are forwarded between interfaces.  It sounds like things are more complicated than I thought.

**Comment by ocelotl** [comment]
This issue is to be migrated when #18 is completed.

**Comment by keinohguchi** [comment]
Hi team,

I'm in a process to use topology/docker framework to create a some simple topology for some of my demo,
by the way, this is really awesome framework, I'm falling in love with it!

And since this demo requires the management connections to all those docker instances, I came here
to get the insight from the pro. :)

What I specifically thinking is to create a simple topology, like [this](https://gist.github.com/keinohguchi/39c52b4c157d3ea0b247), with topology command and connect
all those docker containers, in this case [OPS](http://openswitch.net), through ssh.  I believe OPS only allows the management interface for the ssh connection, I wish this feature comes into the picture.

And in case if this is not the high priority, for whatever reason, I actually want some other way, to create
a ssh connection to all the switches, e.g. passing `-p 10022:22` to the docker instance, so that I can ssh
into the switch through that specific port from the docker host.

Please let me know if this will be got fixed soon or having a way to pass the docker argument, in a meanwhile.  Any info, pointer to take a look at the specific file in this repo, is really appreciated!

Thank you for your support and, again, awesome job, team!

Cheers,

Kei, [Programmer @ OpenSwitch](http://linkedin.com/in/keinohguchi) :)

**Comment by hpathpe** [comment]
Hi,

Do we have work around solution/patch for this.

Thanks

**Comment by jeffesquivels** [comment]
Support for network namespaces inside the container (as well as several network creation of different types) is being worked on #35. This can be used to easily implement an OOBM network for any node that inherits from DockerNode.
